FROM <%= @package[:from] %>
MAINTAINER <%= @basic[:maintainer] %>
LABEL Description="<%= @package[:description] %>" Vendor="<%= @basic[:origin] %>" Version="<%= @basic[:version] %>"

# apiserver listen on port 7443
# watchserver listen on port 8443
# websocket listen on port 9443
EXPOSE  7443 8443 9443

RUN apt-get update -y && \
    apt-get install -y openssl libsodium-dev

# default environment variables
ENV SOURCE_DIR <%= @basic[:home]+"/apiserver/bin/" %>
ENV CONF_FILE api.toml
ENV RIOOS_HOME <%= @basic[:libhome] %>
ENV RIOCONF <%= @basic[:libhome] %>/config/

# volume creation
RUN mkdir -p "$SOURCE_DIR"
VOLUME "$RIOCONF"

WORKDIR "$SOURCE_DIR"

COPY <%= @package[:package]+"/src/"+@package[:git_org]+"/aran/target/release/rioos-apiserver" %> $SOURCE_DIR
COPY <%= @package[:package]+"/src/"+@package[:git_org]+"/aran/tools/config/template" %> "$RIOCONF/template"
COPY <%= @package[:package]+"/src/"+@package[:git_org]+"/aran/tools/license" %> "$RIOOS_HOME"
COPY <%= @package[:package]+"/src/"+@package[:git_org]+"/aran/tools/start-rioosapi" %> "$SOURCE_DIR"
COPY api.toml $RIOCONF

COPY entrypoint.sh $SOURCE_DIR
RUN chmod 755 $SOURCE_DIR/entrypoint.sh
ENTRYPOINT ["<%= @basic[:home]+"/apiserver/bin/entrypoint.sh" %>"]
CMD "<%= @basic[:home]+"/apiserver/bin/start-rioosapi" %>" && /bin/bash
