FROM <%= @package[:from] %>
MAINTAINER <%= @basic[:maintainer] %>
LABEL Description="<%= @package[:description] %>" Vendor="<%= @basic[:origin] %>" Version="<%= @basic[:version] %>"

# exit on error
RUN set -e

# Install VoltDB
# update repo - Trusty does not seem to have add-repo command by default
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
                                   apt-get upgrade --yes --force-yes && \
                                   apt-get -y  --force-yes --no-install-recommends --no-install-suggests install python-software-properties && \
                                   apt-get -y  --force-yes --no-install-recommends --no-install-suggests install software-properties-common

RUN add-apt-repository -y  ppa:openjdk-r/ppa && \
    apt-get update && \
    apt-get install -y --force-yes --no-install-recommends --no-install-suggests openjdk-8-jdk wget


# Set locale-related environment variables
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en

# Set timezone
ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone

# Expose the following ports
# Client Port                   21212
# Admin Port                    21211
# Web Interface Port (httpd)     8080
# Internal Server Port           3021
# Replication Port               5555
# Zookeeper port                 7181
# SSH                              22
EXPOSE 22 3021 5555 7181 8080 8081 9000 21211 21212

ENV VOLTDB_DIST=/opt/voltdb
ENV PATH=$PATH:$VOLTDB_DIST/bin

# set the default version to 6.6
ARG VOLT_KIT_VERSION=<%= @package[:version] %>
# extract location of voltdb directory's suffix. Decopule it from kit-version as there
# can be case where extract location is  different than voltdb kit version
# for eg. voltdb-6.6rc1 is bundle and extract location can be potentially voltdb-6.6
ARG VOLT_DIR_SUFFIX=${VOLT_KIT_VERSION}

# copy voltdb image and layout it out
COPY voltdb-${VOLT_KIT_VERSION}.tar.gz .
RUN tar -zxf voltdb-${VOLT_KIT_VERSION}.tar.gz && \
    mv voltdb-voltdb-${VOLT_KIT_VERSION}  voltdb-${VOLT_KIT_VERSION}  && \
    mkdir ${VOLTDB_DIST} && \
    cp -r voltdb-${VOLT_DIR_SUFFIX}/* $VOLTDB_DIST && \
    rm -r voltdb-${VOLT_DIR_SUFFIX} voltdb-${VOLT_KIT_VERSION}.tar.gz

WORKDIR $VOLTDB_DIST

# fetch the deployment file
COPY deployment.xml ${VOLTDB_DIST}
ENV DEFAULT_DEPLOYMENT=$VOLTDB_DIST/deployment.xml
ENV CUSTOM_CONFIG=/tmp/deployment.xml
ENV LICENSE_FILE=/tmp/license.xml

ENV DIRECTORY_SPEC=/var/voltdb/
RUN mkdir $DIRECTORY_SPEC

COPY docker-entrypoint.sh .
RUN chmod +x docker-entrypoint.sh

ENTRYPOINT ["./docker-entrypoint.sh"]
