stages:
- aventura_rio_bootstrap

rio_bootstrap:
  stage: aventura_rio_bootstrap
    variables:
    CI_DEBUG_TRACE: "true"
  script:
  - cd /home/gitlab-runner/builds/1540ffd4/0/rioos/poochi/rio_bootstrap
  - rake clean
  - rake aventura
  allow_failure: true
