variables:
  NODE_ENV: "test"
  SIMPLECOV: "true"
  GIT_DEPTH: "20"
  HOME: /home/buildrio
  RIO_BUILD_HOME: $CI_PROJECT_DIR
  RIO_BOOTSTRAP_PATH: $RIO_BUILD_HOME/rio_bootstrap
  RIO_NETWORK_PATH: $RIO_BUILD_HOME/rio_network
  RIO_NODELET_PATH: $RIO_BUILD_HOME/rio_nodelet  
  RIO_STORELET_PATH: $RIO_BUILD_HOME/rio_storlet
  RIO_COMMOM_PATH: $RIO_BUILD_HOME/rio_common
  RIO_CONTROLLER_PATH: $RIO_BUILD_HOME/rio_cotroller
  RIO_SCHEDULER_PATH: $RIO_BUILD_HOME/rio_scheduler
  RIO_GULPD_PATH: $RIO_BUILD_HOME/rio_gulpd
  RIO_PROMETHEUS_PATH: $RIO_BUILD_HOME/rio_prometheus
  RIO_VNC_PATH: $RIO_BUILD_HOME/rio_vnc  
  RIO_NILAVU_PATH: $RIO_BUILD_HOME/rio_nilavu
  RIO_RUST_API_PATH: $RIO_BUILD_HOME/rio_api
  RIO_RUST_BLOCKCHAIN_PATH: $RIO_BUILD_HOME/rio_blockchain
  RIO_RUST_MARKETPLACE_PATH: $RIO_BUILD_HOME/rio_marketplace
  RIO_RUST_CLI_PATH: $RIO_BUILD_HOME/rio_cli
  RIO_POWERDNS_PATH: $RIO_BUILD_HOME/rio_powerdns
  RIO_FLUENTBIT_PATH: $RIO_BUILD_HOME/rio_fluentbit
  RIO_ISO_PATH: $RIO_BUILD_HOME/rio_iso
  RIO_MARKETPLACE_PATH: $RIO_BUILD_HOME/marketplaces

before_script:
  - export PATH="$PATH:$HOME/software/go/bin:$HOME/software/node/bin"
  - echo $RIO_BUILD_HOME
  - bundle --version
  - rake --version
  - ruby --version
  - go version
  - node -v
  - sudo docker -v
  - date

after_script:
  - date

stages:
  - build
  - buildimages
  - buildiso
  - buildriomarket
  - shipiso
  - shipriomarket
  - ship
  - post-cleanup

rio_common:
  stage: build
  script:
    - cd $RIO_COMMON_PATH
    - rake clean
    - rake aventura
  allow_failure: true

rio_ship:
  stage: shipiso
  script:
    - cd $RIO_BUILD_HOME    
  allow_failure: true

rio_ship:
  stage: shipriomarket
  script:
    - cd $RIO_BUILD_HOME   
  allow_failure: true

rio_ship:
  stage: ship
  script:
    - cd $RIO_BUILD_HOME
    - rake ship:clean
    - rake ship:aventura
  allow_failure: true

rio_done:
  stage: post-cleanup
  script:
    - cd $RIO_BUILD_HOME
    - find . -type d -name "build" -exec rmdir {} \;
  allow_failure: true  