stages:
  - aventura_rio_bootstrap

rio_bootstrap:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: aventura_rio_bootstrap
  script:
    - cd $CI_PROJECT_DIR/rio_bootstrap
    - rake clean
    - rake aventura
  allow_failure: true
