variables:
  NODE_ENV: "test"
  SIMPLECOV: "true"
  GIT_DEPTH: "20"
  HOME: /home/buildrio
  RIO_BUILD_HOME: /home/gitlab-runner/$CI_PROJECT_DIR
  RIO_BOOTSTRAP_PATH: $RIO_BUILD_HOME/rio_bootstrap
  RIO_NETWORK_PATH: $RIO_BUILD_HOME/rio_network
  RIO_NODELET_PATH: ${RIO_BUILD_HOME}/rio_nodelet
  RIO_NODELET_GOPATH: ${RIO_NODELET_PATH}/build/aventura/rioos_nodelet
  RIO_STORELET_PATH: ${RIO_BUILD_HOME}/rio_storlet
  RIO_STORELET_GOPATH: ${RIO_STORELET_PATH}/build/aventura/rioos_storlet
  RIO_COMMOM_PATH: $RIO_BUILD_HOME/rio_common
  RIO_CONTROLLER_PATH: $RIO_BUILD_HOME/rio_cotroller
  RIO_SCHEDULER_PATH: $RIO_BUILD_HOME/rio_scheduler
  RIO_GULPD_PATH: $RIO_BUILD_HOME/rio_gulpd
  RIO_PROMETHEUS_PATH: $RIO_BUILD_HOME/rio_prometheus
  RIO_VNC_PATH: $RIO_BUILD_HOME/rio_vnc
  RIO_NILAVU_PATH: $RIO_BUILD_HOME/rio_nilavu
  RIO_RUST_API_PATH: $RIO_BUILD_HOME/rio_api
  RIO_RUST_BLOCKCHAIN_PATH: $RIO_BUILD_HOME/rio_blockchain
  RIO_RUST_MARKETPLACE_PATH: $RIO_BUILD_HOME/rio_marketplace
  RIO_RUST_CLI_PATH: $RIO_BUILD_HOME/rio_cli
  RIO_POWERDNS_PATH: $RIO_BUILD_HOME/rio_powerdns
  RIO_FLUENTBIT_PATH: $RIO_BUILD_HOME/rio_fluentbit
  RIO_ISO_PATH: $RIO_BUILD_HOME/rio_iso
  RIO_MARKETPLACE_PATH: $RIO_BUILD_HOME/marketplaces

before_script:
  - export PATH="$PATH:$HOME/software/go/bin:$HOME/software/node/bin"
  - bundle --version
  - rake --version
  - ruby --version
  - go version
  - node -v
  - sudo docker -v
  - date

after_script:
  - date

stages:
  - build
  - buildimages
  - buildiso
  - buildriomarket
  - shipiso
  - shipriomarket
  - ship
  - post-cleanup

rio_common:
  stage: build
  artifacts:
    untracked: true
  script:
    - cd rio_common
    - rake clean
    - rake aventura
  allow_failure: true

rio_network:
  stage: build
  artifacts:
    untracked: true
  script:
    - cd rio_network
    - rake clean
    - rake aventura
  allow_failure: true

rio_bootstrap:
  stage: build
  artifacts:
    untracked: true
  script:
    - cd rio_bootstrap
    - rake clean
    - rake aventura
  allow_failure: true

rio_storlet:
  stage: build
  artifacts:
    untracked: true
  script:
    - export GOPATH=$RIO_STORELET_GOPATH
    - echo $RIO_STORLET_GOPATH
    - cd rio_storlet
    - rake clean
    - rake aventura
  allow_failure: true

rio_nodelet:
  stage: build
  artifacts:
    untracked: true
  script:
    - export GOPATH=$RIO_NODELET_GOPATH
    - echo $RIO_NODELET_GOPATH
    - cd rio_nodelet
    - rake clean
    - rake aventura
  allow_failure: true

rio_ship:
  stage: ship
  dependencies:
    - rio_common
    - rio_network
    - rio_bootstrap
    - rio_storlet
    - rio_nodelet
  script:
    - sudo rake ship:clean
    - sudo rake ship:aventura
  allow_failure: true
