FROM <%= @package[:from] %>
MAINTAINER <%= @basic[:maintainer] %>
LABEL Description="<%= @package[:description] %>" Vendor="<%= @basic[:origin] %>" Version="<%= @basic[:version] %>"

# vncserver on port 8000
EXPOSE 8000

RUN apk update
RUN mkdir -p <%= @basic[:home]+"/"+@package[:package] %>
WORKDIR <%= @basic[:home]+"/"+@package[:package] %>

COPY <%= @package[:package]+"/src/"+@package[:git_org]+"/vncserver" %> <%= @basic[:home]+"/"+@package[:package] %>

# Install npm
RUN npm install

# run ember server on container start
CMD ["/usr/local/bin/node", "vnc_monitor.js", "--port", "8000"]
