#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2017 RioCorp inc.                                                #
#                                                                            #
#--------------------------------------------------------------------------- #

# Checks if the loopback interface is not configured and adds 127.0.0.1.
# This fixes a problem with old Ubuntu 14.04 distros that leave loopback
# IP unconfigured when restarting network. This does not happen with
# Ubuntu 14.04.4

ip_info="$(ip -o -4 address show lo)"

if [ -z "$ip_info" ]; then
    ip addr add 127.0.0.1/8 dev lo
    ip link set lo up
fi
