#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2017 RioCorp inc.                                                #
#                                                                            #
#--------------------------------------------------------------------------- #

if [ -z "${USERNAME}" ]; then
    USERNAME=root
fi

if ! getent passwd "${USERNAME}" > /dev/null 2>&1; then
    useradd -m "${USERNAME}"
fi

if [ -n "${CRYPTED_PASSWORD_BASE64}" ]; then
    CRYPTED_PASSWORD=$(echo $CRYPTED_PASSWORD_BASE64 | base64 -d)
    usermod -p "${CRYPTED_PASSWORD}" "${USERNAME}"
elif [ -n "${PASSWORD_BASE64}" ]; then
    PASSWORD=$(echo $PASSWORD_BASE64 | base64 -d)
    chpasswd <<< "${USERNAME}:${PASSWORD}"
elif [ -n "${CRYPTED_PASSWORD}" ]; then
    usermod -p "${CRYPTED_PASSWORD}" "${USERNAME}"
elif [ -n "${PASSWORD}" ]; then
    chpasswd <<< "${USERNAME}:${PASSWORD}"
fi
