FROM <%= @package[:from] %>
MAINTAINER <%= @basic[:maintainer] %>
LABEL Description="<%= @package[:description] %>" Vendor="<%= @basic[:origin] %>" Version="<%= @basic[:version] %>"

# marketplace run on port 6443
EXPOSE  6443

RUN apt-get update -y && \
    apt-get install -y openssl libsodium-dev

# default environment variables
ENV SOURCE_DIR <%= @basic[:home]+"/marketplace/bin/" %>
ENV CONF_FILE marketplace.toml
ENV RIOCONF <%= @basic[:libhome] %>/config

# volume creation
RUN mkdir -p "$SOURCE_DIR"

RUN mkdir -p "$RIOCONF/pullcache"

VOLUME "$RIOCONF"

WORKDIR "$SOURCE_DIR"
COPY <%= @package[:package]+"/src/"+@package[:git_org]+"/aran/target/release/rioos-marketplaces" %> $SOURCE_DIR

COPY entrypoint.sh $SOURCE_DIR
RUN chmod 755 $SOURCE_DIR/entrypoint.sh
ENTRYPOINT ["<%= @basic[:home]+"/marketplace/bin/entrypoint.sh" %>"]

CMD  ["marketplace"]
