require File.expand_path(File.join(File.dirname(__FILE__),'..', 'lib', 'pkg.rb'))

require 'pkg/static/data'

task :default => :trusty

task :clean do
  Pkg::Util::File.rmdir(Pkg::Common.build_dir)
end

task :initnix do
  Pkg::Util::File.mkdir_p(Pkg::Common.distro_build_dir)
end

task :nix => [:initnix] do
  Pkg::Builder.new(Pkg::Common.distro_dir, Pkg::Common.distro_build_dir, Pkg::Data.COMMON).exec
end

task :trusty   do
  Pkg::Common.distro("trusty")
  Rake::Task[:nix].invoke
end

task :xenial do
  Pkg::Common.distro("xenial")
  Rake::Task[:nix].invoke
end

task :centos7 do
  Pkg::Common.distro("centos7")
  Rake::Task[:nix].invoke
end
