FROM <%= @package[:from] %>
MAINTAINER <%= @basic[:maintainer] %>
LABEL Description="<%= @package[:description] %>" Vendor="<%= @basic[:origin] %>" Version="<%= @basic[:version] %>"

# yarn server on port 4200
EXPOSE 8000 49153 5779

# install dependencies
RUN apk update && \
    apk upgrade && \
    apk add git yarn

# default environment variables
ENV SOURCE_DIR <%= @basic[:home]+"/"+@package[:package] %>
ENV RIOCONF <%= @basic[:libhome] %>/config/
ENV CONF_FILE ui.toml

# volume creation
RUN mkdir -p "$SOURCE_DIR"
RUN mkdir -p "$RIOCONF"
VOLUME "$RIOCONF"

WORKDIR $SOURCE_DIR

COPY <%= @package[:package]+"/src/"+@package[:git_org]+"/nilavu" %> "$SOURCE_DIR"
COPY <%= @package[:package]+"/src/"+@package[:git_org]+"/nilavu/config/config/ui.toml" %> "$RIOCONF"
COPY entrypoint.sh $SOURCE_DIR
RUN chmod 755 $SOURCE_DIR/entrypoint.sh
ENTRYPOINT ["<%= @basic[:home]+"/"+@package[:package]+"/entrypoint.sh" %>"]

# run yarn server on container start
CMD ["ui"]
