require File.expand_path(File.join(File.dirname(__FILE__),'..', 'lib', 'pkg.rb'))

require 'pkg/static/data'

task :default => :trusty

task :clean do
  Pkg::Util::File.rmdir(Pkg::Common.build_dir)
end

task :initnix do
  Pkg::Util::File.mkdir_p(Pkg::Common.distro_build_dir)
end

task :nix => [:initnix] do
  Pkg::Builder.new(Pkg::Common.distro_dir, Pkg::Common.distro_build_dir, Pkg::Data.VNETWORK).exec
end

task :aventura do
  Pkg::Common.distro("aventura")
  Rake::Task[:nix].invoke
end
