# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# scrape metrics from this promethues server
# port 9090 - metrics from prometheus server
# port 8081 - metrics from opentstb
# port 9104
scrape_configs:
- job_name: 'prometheus'

  static_configs:
  - targets: ['localhost:9090', 'localhost:9104', 'localhost:8081']

# scrape metrics from all containers of Rio/OS in a datacenter
# port: 10254 - scrap metrics from all the containers deployed in Rio/OS
- job_name: 'rioos_sh_containers'

  rioos_sd_configs:
  - role: 'node'

    api_server: 'https://localhost:7443'

    watch_server: 'https://localhost:8443'

    metric_port: '10254'

    tls_config:
      ca_file: /var/lib/rioos/config/server-ca.cert.pem
      cert_file: /var/lib/rioos/config/client-prometheus.cert.pem
      key_file: /var/lib/rioos/config/client-prometheus.key

    service-account-private-key-file: /var/lib/rioos/config/service-account.key

# scrape metrics from all machines of Rio/OS in a datacenter
# port: 10252 - scrap metrics from all the machines deployed in Rio/OS
- job_name: 'rioos_sh_machines'

  rioos_sd_configs:
  - role: 'assembly'

    api_server: 'https://localhost:7443'

    watch_server: 'https://localhost:8443'

    metric_port: '10252'

    tls_config:
      ca_file: /var/lib/rioos/config/server-ca.cert.pem
      cert_file: /var/lib/rioos/config/client-prometheus.cert.pem
      key_file: /var/lib/rioos/config/client-prometheus.key

    service-account-private-key-file: /var/lib/rioos/config/service-account.key

  relabel_configs:
  - source_labels: [__meta_rioos_assembly_id]
    action: replace
    target_label: rioos_assembly_id
  - source_labels: [__meta_rioos_assemblyfactory_id]
    action: replace
    target_label: rioos_assemblyfactory_id
  - source_labels: [__meta_rioos_os_name]
    action: replace
    target_label: rioos_os_name


# scrape metrics from all nodes of Rio/OS in a datacenter
# port: 10250 - scrap metrics from the nodelet (node_exporter)
- job_name: 'rioos_sh_nodes'

  rioos_sd_configs:
  - role: 'node'

    api_server: 'https://localhost:7443'

    watch_server: 'https://localhost:8443'

    metric_port: '10250'

    tls_config:
      ca_file: /var/lib/rioos/config/server-ca.cert.pem
      cert_file: /var/lib/rioos/config/client-prometheus.cert.pem
      key_file: /var/lib/rioos/config/client-prometheus.key

    service-account-private-key-file: /var/lib/rioos/config/service-account.key

  relabel_configs:
  - source_labels: [__meta_rioos_node_name]
    action: replace
    target_label: rioos_node_name
  - source_labels: [__meta_rioos_node_address]
    action: replace
    target_label: rioos_node_address
  - action: labelmap
    regex: __meta_rioos_node_address_(.+)
