FROM <%= @package[:from] %>
MAINTAINER <%= @basic[:maintainer] %>
LABEL Description="<%= @package[:description] %>" Vendor="<%= @basic[:origin] %>" Version="<%= @basic[:version] %>"

# Block chain run on port 7000
EXPOSE 7000

RUN apt-get update -y && \
    apt-get install -y openssl libsodium-dev

# default environment variables
ENV SOURCE_DIR <%= @basic[:home]+"/blockchain/bin/" %>
ENV CONF_FILE api.toml
ENV RIOCONF <%= @basic[:libhome] %>/blockchain

# volume creation
RUN mkdir -p "$SOURCE_DIR"

VOLUME "$RIOCONF"

WORKDIR "$SOURCE_DIR"
COPY <%= @package[:package]+"/src/"+@package[:git_org]+"/aran/target/release/rioos-blockchain-server" %> $SOURCE_DIR

COPY entrypoint.sh $SOURCE_DIR
RUN chmod 755 $SOURCE_DIR/entrypoint.sh
ENTRYPOINT ["<%= @basic[:home]+"/blockchain/bin/entrypoint.sh" %>"]

CMD  ["blockchain"]
